### ISSUE TITLE
Request to Include Flipt Engine Header File for Go Client SDK

### ISSUE THREAD

**Issue by sylwang** [flipt-io/flipt-client-sdks#187] opened 2024-03-25 20:50 UTC
Hi there!

My team has been running into an issue below:
```
2024-03-25 13:43:21 # go.flipt.io/flipt-client
2024-03-25 13:43:21 /cache/go.flipt.io/flipt-client@v0.4.3/evaluation.go:9:10: fatal error: ./ext/flipt_engine.h: No such file or directory
2024-03-25 13:43:21     9 | #include "./ext/flipt_engine.h"
2024-03-25 13:43:21       |          ^~~~~~~~~~~~~~~~~~~~~~
2024-03-25 13:43:21 compilation terminated.
```

We imported the Go client SDKs and included it in our `go.mod` file for our project. Since there is a requirement for including the flipt engine header file, we had to fork the flipt client SDKs into our project and then manually modify the `/ext` directory to include this header file.

Golang doesn't allow modifications to an imported library, so the only way to solve this problem is to fork the repo and manually include the header file in `/ext` directory. That is something we want to avoid doing for our project. 

What are your suggestions? And I wonder Is there a reason why this flipt engine header file wasn't included (if it is just a static header file) for the Go client SDKs?

Thank you!

**Comment by markphelps** [comment] 2024-03-25 21:01
Thanks for reporiting @sylwang !

I may have a fix in #188 , unfortunately the only real way I can test it is by creating a new release of the Go SDK, because of how go works with modules/github/etc.

We have to effectively copy the subdirectory of `flipt-client-go` from this repo and push it to it's own repo: https://github.com/flipt-io/flipt-client-sdks/blob/a44168b902bb20092174a209df59e03ba8a7652f/build/main.go#L142-L148

https://github.com/flipt-io/flipt-client-go

Im thinking this gitignore caused the libs and header file to be skipped during the copy. We'll know if it works shortly!

**Comment by markphelps** [comment] 2024-03-25 21:03
DIdnt work.. still looking

**Comment by sylwang** [comment] 2024-03-25 21:07
Hi @markphelps ! Thank you for responding so quickly. Really appreciate that you're looking into this. We will stay tuned!

**Comment by sylwang** [comment] 2024-03-25 21:27
I just tried to use the latest version v0.4.4 using `go get`
```
sy.wang@F2L0GF3HWP control-plane % go get "go.flipt.io/flipt-client"
go: downloading go.flipt.io/flipt-client v0.4.4
go: added go.flipt.io/flipt-client v0.4.4
```
and still saw the same issue. 
```
2024-03-25 14:25:27 # go.flipt.io/flipt-client
2024-03-25 14:25:27 /cache/go.flipt.io/flipt-client@v0.4.4/evaluation.go:9:10: fatal error: ./ext/flipt_engine.h: No such file or directory
2024-03-25 14:25:27     9 | #include "./ext/flipt_engine.h"
2024-03-25 14:25:27       |          ^~~~~~~~~~~~~~~~~~~~~~
2024-03-25 14:25:27 compilation terminated.
```

Did I miss any step in terms of getting the latest update (the fix) you added? Thanks!

**Comment by markphelps** [comment] 2024-03-25 21:29
Nope sorry, GH auto-closed :(. Still working on it unfortunately.. will keep you updated!

**Comment by sylwang** [comment] 2024-03-25 21:30
Ohh, no worries : ) Thank you Mark!

**Comment by markphelps** [comment] 2024-03-25 21:55
ugh i just noticed that the path in the go SDK points to `/ext/flipt_engine.h` but the file is actually in `ext/linux_x86_64/flipt_engine.h`.. lmk if it doesn't work still

**Comment by sylwang** [comment] 2024-03-25 22:08
Same issue still, header file not found : (. I was using `go.flipt.io/flipt-client v0.4.4`.

**Comment by markphelps** [comment] 2024-03-25 22:43
What's interesting is that Rust or cbindgen is only generating the `.h` file for when the target is `linux_x86_64`. We should probably dig into why tbh. Is your target linux x64 by chance? if so then you are right we could make it `${SRCDIR}/ext/${OS}_${ARCH}/flipt_engine.h`

**Comment by sylwang** [comment] 2024-03-25 22:47
Unfortunately, my target is `linux_arm64`. We're running our project in a Docker container, so the target could be different for different developers on our team.

**Comment by sylwang** [comment] 2024-03-25 23:19
The easiest solution I can think of, is to put the generated header file under `${SRCDIR}/ext/flipt_engine.h or ./ext/flipt_engine.h`, since this is where the go SDK tried to look for the header file?

**Comment by markphelps** [comment] 2024-03-26 00:05
> cbindgen should be able to generate header files for a variety of targets, as long as those targets are compatible with cbindgen. Since cbindgen generates header files based on the Rust code and its configuration, could it be the configuration setting in the Rust code that caused the issue with only generating .h file when the target is linux_x86_64?

I think you are right that there is something odd going on with either how we are invoking cbindgen (via a [build.rs](https://github.com/flipt-io/flipt-client-sdks/blob/main/flipt-engine-ffi/build.rs) script) or something going on with how our packaging works in GitHub Actions (see: [RELEASE.md](https://github.com/flipt-io/flipt-client-sdks/blob/main/RELEASE.md))

For example, for the linux x86 build we can see that the .h gets put in the archive, however for both the darwin (arm) and linux (arm) the tar command says the file is not found:

- [linux x86](https://github.com/flipt-io/flipt-client-sdks/actions/runs/8403994232/job/23015099766#step:8:11)
- [darwin (arm)](https://github.com/flipt-io/flipt-client-sdks/actions/runs/8403994232/job/23015099932#step:8:11)
- [linux (arm)](https://github.com/flipt-io/flipt-client-sdks/actions/runs/8403994232/job/23015099854#step:8:11)

> The easiest solution I can think of, is to put the generated header file under ${SRCDIR}/ext/flipt_engine.h or ./ext/flipt_engine.h, since this is where the go SDK tried to look for the header file?

agreed Im just trying to figure out how to make this work cleanly with our GitHub actions/convoluted release process since the .h file only gets generated when built for x86 linux.

another option is to simply check-in in the .h file for now (and remove cbindgen) into a known location and then copy it into each library when packaging the sdks

**Comment by sylwang** [comment] 2024-03-26 00:16
The second option sounds like a good quick fix! Could you guys temporarily fix this using this option while working out a cleaner way to address this? My team is hoping to have a feature flag solution working as soon as possible, so that would be highly appreciated!

**Comment by markphelps** [comment] 2024-03-26 00:28
Yes will do in the morning (sorry getting late here) hope that is ok!

**Comment by sylwang** [comment] 2024-03-26 00:30
No worries. Thank you for all your help. Goodnight! 🌙

**Comment by markphelps** [comment] 2024-03-26 15:44
@sylwang could you try giving 0.4.5 of the go SDK a try?

I think it should work now:
![CleanShot 2024-03-26 at 11 43 01](https://github.com/flipt-io/flipt-client-sdks/assets/209477/66612c69-d92c-4f9b-9d44-177862541a6f)

**Comment by sylwang** [comment] 2024-03-26 16:02
The issue with the header file is now fixed!! Thank you so much for your assistance @markphelps! I have one final clarification question:

While building our program that uses the flipt go client SDK in a Docker container, we got this error:
`error while loading shared libraries: libfliptengine.so: cannot open shared object file: No such file or directory`

After building the .so file and copying it into the shared library path under `/usr/lib/`, it was fixed. Is it expected for us to compile the .so file ourselves and manually copy it over to our system shared library path?

**Comment by markphelps** [comment] 2024-03-26 16:06
No, the CGO directives should tell Go where to look for the `libfliptengine` lib, which are included in the module:

![CleanShot 2024-03-26 at 12 04 54](https://github.com/flipt-io/flipt-client-sdks/assets/209477/59ee06ee-e0c1-4657-97a3-58208598ceca)

Let me try to reproduce

**Comment by markphelps** [comment] 2024-03-26 16:21
I managed to reproduce here 🤦🏻 https://github.com/flipt-io/fliptgosdk/tree/main

Investigating.. sorry FFI is a pain

**Comment by sylwang** [comment] 2024-03-26 16:26
Glad that you could reproduce it... It was indeed a pain since I was digging into the repository and thinking that I needed to manually compile the flipt engine and .so files, but these were not mentioned in the README for the go client sdk! It seems that I overcomplicated things then, it's expected that we should be able to just use the go client sdk using `go get`. That's a relief!

**Comment by markphelps** [comment] 2024-03-26 18:04
wooowee just went down a serious rabbit hole and I think we finally figured it out

So.. turns out were weren't correctly stripping the libraries of debug symbols.. so when trying to link the library from Go.. I guess it was then trying to load something that the library itself was pointing to.. but this would only exist where the library was built (in GitHub Actions) 

So when trying to run the example program.. I would get errors like:

```
dyld[71487]: Library not loaded: /Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib
  Referenced from: <09DBBA41-36E5-3286-89D9-C1FF59F6E55D> /private/var/folders/r9/zzvt56zx7pj5ckkh046d77940000gn/T/go-build1707049622/b001/exe/main
  Reason: tried: '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file)
```

```
'/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/
```

Is the path on GitHub Actions runner where the library was built. I couldn't figure out how the library itself knew where it was built, or why it was trying to reference these paths

So.. I poped the dylib (on my local mac machine) into a dissassembler, and low and behold the build paths are in the library itself!

![CleanShot 2024-03-26 at 13 59 54](https://github.com/flipt-io/flipt-client-sdks/assets/209477/4282cdd6-10df-450c-adfe-efc1de97226a)

So I then set cargo to correctly strip the library at build time.. which removed these debug symbols by setting:

```
[profile.release]
strip = true
```

in the root cargo.toml

Then I tried to load this new built library locally and vioala! it was able to find it and link it correctly!

So.. this means we need to create one more (hopefully) release of both the engine and the Go SDK to finally (hopefully) resolve this

**Comment by sylwang** [comment] 2024-03-26 18:07
Woohoo!! Thank you for sharing the details on your debugging process. Fun stuff : ) Finger crossed everything works!

**Comment by markphelps** [comment] 2024-03-26 20:20
Ok.. im still at a loss unfortunately.

The new release (go SDK 0.4.6) still gives me the same error 

There still seems to be a difference between what is being build in CI (Actions) and what gets built locally, both running (so I think) `cargo build --release`

When I run `cargo build --release` locally (Mac ARM), it builds a release library that is around 8M. 

When I download the released engine for Mac ARM from our CI pipeline artificats, I get a library around 6.3MB..

I've copied both to the Go Module directory on my localhost: `/Users/markphelps/go/pkg/mod/go.flipt.io/flipt-client@v0.4.6/ext/darwin_arm64`

```
-rwxr-xr-x@ 1 root        staff  7982072 Mar 26 16:10 libfliptengine.dylib
-rwxr-xr-x@ 1 root        staff  6385432 Mar 26 15:57 libfliptengine.remote.dylib
-r--r--r--  1 markphelps  staff   798424 Mar 26 14:54 libfliptengine.rlib
```

I named them differently so I can swap between them for running my test go app, that is the same code [here](https://github.com/flipt-io/fliptgosdk/blob/main/main.go)

Here is what happens for each:

## libfliptengine.dylib built locally ✅ 

works, but panics because I dont have Flipt running so it cant find the flag state.. but at least linkage works

```
/tmp/gosdk - [main] » go clean -cache
/tmp/gosdk - [main] » go run main.go
thread '<unnamed>' panicked at flipt-engine-ffi/src/lib.rs:205:74:
called `Result::unwrap()` on an `Err` value: Server("failed to make request: error sending request for url (http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default)")
```


## libfliptengine.dylib built in CI ❌ 

Does not work, same error as before

```
/tmp/gosdk - [main] » go clean -cache
/tmp/gosdk - [main] » go run main.go
dyld[20306]: Library not loaded: /Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib
  Referenced from: <E3A04DF9-0C1C-3069-AA3A-1320F8242A75> /private/var/folders/r9/zzvt56zx7pj5ckkh046d77940000gn/T/go-build2268303618/b001/exe/main
  Reason: tried: '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file)
signal: abort trap
```

I will likely need some help figuring this out or just more time as I've spent pretty much all day on it and still cant seem to get to the bottom of it

**Comment by sylwang** [comment] 2024-03-26 20:33
That's frustrating : (  It seems that somehow the CI pipeline didn't build the binaries the same way as how they were built locally.

**Comment by markphelps** [comment] 2024-03-26 20:49
Ok now we're getting somewhere..

When I run `otool -L` on both dylibs I get 

## Local libfliptengine

```
ext/darwin_arm64 » otool -L libfliptengine.dylib
libfliptengine.dylib:
	/Users/markphelps/workspace/flipt-client-sdks/target/release/deps/libfliptengine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1296.60.3)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 61040.61.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2202.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

## CI libfliptengine

```
ext/darwin_arm64 » otool -L libfliptengine.remote.dylib
libfliptengine.remote.dylib:
	/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1241.60.3)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60420.60.24)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

So it does seem like they are linking against themselves?

I think https://github.com/flipt-io/flipt-client-sdks/issues/187#issuecomment-2021390135 was actually a false-positive because once I do `rm -f /Users/markphelps/workspace/flipt-client-sdks/target/release/deps/libfliptengine.dylib` and try to re-run the example I do infact get:

```
dyld[63116]: Library not loaded: /Users/markphelps/workspace/flipt-client-sdks/target/release/deps/libfliptengine.dylib
  Referenced from: <8618D4A5-3AE3-3D5C-844D-BF94102D8172> /private/var/folders/r9/zzvt56zx7pj5ckkh046d77940000gn/T/go-build3707976841/b001/exe/main
```

So it seems like the type of library we're building is incorrect, as idk why it would be trying to link against itself.. 

But tbh I don't know how this would have ever worked in other languages..

**Comment by sylwang** [comment] 2024-03-26 21:00
I noticed that in the CI, the .dylib file was named as `libfliptengine.remote.dylib` whereas locally it was named as `libfliptengine.dylib`. Not sure if that would make a difference...

Also, there are version mismatches for all the dependencies between the local and CI environment. For example, locally `1336.61.1` was used in `/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)`, and in CI, `1319.0.0` was used in `/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)`.

**Comment by markphelps** [comment] 2024-03-26 21:15
> I noticed that in the CI, the .dylib file was named as `libfliptengine.remote.dylib` whereas locally it was named as `libfliptengine.dylib`. Not sure if that would make a difference...
> 

It was named `libfliptengine.dylib` in CI too, I just renamed it locally after downloading it and putting it in place so that I could switch between the CI built lib and the local built lib easily

`mv libfliptengine.dylib libfliptengine.local.dylib`
`mv libfliptengine.remote.dylib libfliptengine.dylb`

**Comment by markphelps** [comment] 2024-03-26 21:19
> Also, there are version mismatches for all the dependencies between the local and CI environment. Are the ones in the CI environment out dated? For example, locally 1336.61.1 was used in /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1), and in CI, 1319.0.0 was used in /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0).

yeah this is probably true, but im not sure its the real culprit. I still need to understand why the libraries seem to require themselves if that makes sense

**Comment by markphelps** [comment] 2024-03-26 21:39
Here is what ChatGPT has to say:

```
Display of the Install Name

What's often happening in these cases, especially for the main entry shown right under the command output (libfliptengine.remote.dylib: in your example), is that otool -L is displaying the install name of the library. The install name (LC_ID_DYLIB in Mach-O terminology) is a path embedded in the dynamic library that indicates where the library expects to be found at runtime. This is not an indication of a dependency but rather a self-reference pointing to its own intended location in the filesystem.

For dynamically linked libraries, the install name is used by the dynamic linker at runtime to locate the library. If you move the library to a different location, you might need to update its install name (using the install_name_tool utility on macOS) so that dependent applications can still find it.

In your output, the first path shown after the library name is actually this install name, not a dependency. The actual dependencies follow, listing other libraries and frameworks the libfliptengine.remote.dylib depends on for functionality, like the SystemConfiguration and Security frameworks.

Understanding these nuances helps in interpreting otool -L output correctly and managing dynamic libraries on macOS and other Unix-like systems effectively.
```

**Comment by sylwang** [comment] 2024-03-26 21:43
That makes sense! Although, `libfliptengine.remote.dylib` was shown as part of the dependency tree, it doesn't mean that it is self referencing. That's not an issue then. Since "install name" was mentioned, I wonder the reason this .dylib cannot be found could be related to the "install name" being different in the CI environment? Perhaps if "install name" is set up correctly in the CI environment, it will work...

**Comment by erka** [comment] 2024-03-26 23:19
When I do `go build -ldflags "-v" main.go` on `golang:1.21.8-bookworm` I get the 2.5Mb binary while `libfliptengine.so` is 13Mb. 
I probably could run it with `LD_LIBRARY_PATH=/go/pkg/mod/go.flipt.io/flipt-client@v0.4.6/ext/linux_x86_64 ./main`
That is a dynamic library and it could not be linked into binary, right? Should there be crate_type `staticlib` for `go`?

**Comment by markphelps** [comment] 2024-03-26 23:43
> That is a dynamic library and it could not be linked into binary, right? Should there be crate_type staticlib for go?

I tried this but got a bunch of other MacOS linkage errors like:
```
ld: Undefined symbols:
  _AuthorizationCreate, referenced from:
      security_framework::authorization::Authorization::new::hc6260ba8b95901ff in libfliptengine.a[106](security_framework-50612e4ebcfe3fc6.security_framework.c31b39020eacc23e-cgu.13.rcgu.o)
  _AuthorizationCreateFromExternalForm, referenced from:
      _$LT$security_framework..authorization..Authorization$u20$as$u20$core..convert..TryFrom$LT$security_framework_sys..authorization..AuthorizationExternalForm$GT$$GT$::try_from::hca529f64977c0d2a in libfliptengine.a[106](security_framework-50612e4ebcfe3fc6.security_framework.c31b39020eacc23e-cgu.13.rcgu.o)
      security_framework::authorization::Authorization::from_external_form::h13278ee350a82de8 in libfliptengine.a[106](security_framework-50612e4ebcfe3fc6.security_framework.c31b39020eacc23e-cgu.13.rcgu.o)
```

I think I finally figured out the magical incantation to use for the `#cgo directives`:

```
/*
#cgo darwin,arm64 LDFLAGS: -L./ext/darwin_arm64 -lfliptengine -Wl,-rpath -Wl,./ext/darwin_arm64
#cgo linux,arm64 LDFLAGS: -L./ext/linux_arm64 -lfliptengine -Wl,-rpath -Wl,./ext/linux_arm64
#cgo linux,amd64 LDFLAGS: -L./ext/linux_x86_64 -lfliptengine -Wl,-rpath -Wl,./ext/linux_x86_64
#include <string.h>
#include <stdlib.h>
#include "./ext/flipt_engine.h"
*/
```

This should allow the library to finally find the relative DLLs . Let me do a bit more testing before I say its working though.. I've been burned before.

**Comment by markphelps** [comment] 2024-03-27 00:40
```
/tmp/gosdk - [main●] » LD_LIBRARY_PATH=~/go/pkg/mod/go.flipt.io/flipt-client@v0.4.7/ext/darwin_arm64 ./main
dyld[84247]: Library not loaded: /Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib
  Referenced from: <EF0870F7-B765-3DFD-9E4E-8E1DA9F6C1D1> /private/tmp/gosdk/main
  Reason: tried: '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file)
```

its still looking in the wrong place :( cc @erka

**Comment by erka** [comment] 2024-03-27 12:39
> ```
> /tmp/gosdk - [main●] » LD_LIBRARY_PATH=~/go/pkg/mod/go.flipt.io/flipt-client@v0.4.7/ext/darwin_arm64 ./main
> dyld[84247]: Library not loaded: /Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib
>   Referenced from: <EF0870F7-B765-3DFD-9E4E-8E1DA9F6C1D1> /private/tmp/gosdk/main
>   Reason: tried: '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file), '/Users/runner/work/flipt-client-sdks/flipt-client-sdks/target/aarch64-apple-darwin/release/deps/libfliptengine.dylib' (no such file)
> ```
> 
> its still looking in the wrong place :( 


@markphelps  For mac you use `DYLD_LIBRARY_PATH`. Like 

```DYLD_LIBRARY_PATH=~/go/pkg/mod/go.flipt.io/flipt-client@v0.4.7/ext/darwin_arm64 ./main```

**Comment by sylwang** [comment] 2024-03-27 16:47
Thank you @markphelps and @erka ! This unblocks me at the moment. I'll keep an eye on any incoming update. Please let me know if you guys get the dynamic linking working with `go get`.

@markphelps I appreciate that you spent a lot of time debugging this and responding in a timely manner, Mark. Thanks a lot! 🙏

**Comment by markphelps** [comment] 2024-03-27 17:15
Great! I will close this issue then and open up a new one to try and figure out how to support relative linking to the library from the go module.

Will also add a note to the Go Readme describing the necessary env vars for now

**Closed by markphelps** 2024-03-27 17:15 UTC
